[package]
name = "grind_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "grind_engine"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.39"
rusqlite = { version = "0.33.0", features = ["chrono"] }
serde = { version = "1.0.218", features = ["derive"] }
